/* =========================================================================
   DỮ LIỆU ĐỀ THI THỬ LỊCH SỬ TỐT NGHIỆP THPT (CẤU TRÚC 2026)
   Bản quyền thuộc về số ĐT: 0943.930.787
========================================================================= */

const dataMocktest = {};

// =========================================================================
// ĐỀ THI THỬ SỐ 1
// =========================================================================
dataMocktest[1] = [
    { type: 'mcq', text: "Câu 1. Trật tự thế giới hai cực I-an-ta được hình thành trên cơ sở những quyết định của hội nghị nào sau đây?", options: ["Hội nghị I-an-ta.", "Hội nghị Pốt-đam.", "Hội nghị Pa-ri.", "Hội nghị Giơ-ne-vơ."], answer: 0 },
    { type: 'mcq', text: "Câu 2. Quốc gia nào sau đây là nơi khởi nguồn của cuộc cách mạng khoa học - kĩ thuật hiện đại từ những năm 40 của thế kỉ XX?", options: ["Anh.", "Pháp.", "Mỹ.", "Nhật Bản."], answer: 2 },
    { type: 'mcq', text: "Câu 3. Sự kiện nào sau đây đánh dấu chủ nghĩa xã hội đã vượt ra khỏi phạm vi một nước trở thành hệ thống thế giới?", options: ["Thắng lợi của Cách mạng tháng Mười Nga (1917).", "Thắng lợi của các nước Dân chủ nhân dân Đông Âu (1945-1949).", "Sự ra đời của nước Cộng hòa Nhân dân Trung Hoa (1949).", "Thắng lợi của Cách mạng Cu-ba (1959)."], answer: 1 },
    { type: 'mcq', text: "Câu 4. Hiệp hội các quốc gia Đông Nam Á (ASEAN) được thành lập vào năm 1967 tại đâu?", options: ["Băng Cốc (Thái Lan).", "Ba-li (In-đô-nê-xi-a).", "Gia-các-ta (In-đô-nê-xi-a).", "Ma-ni-la (Phi-líp-pin)."], answer: 0 },
    { type: 'mcq', text: "Câu 5. Lực lượng xã hội nào ở Việt Nam ra đời do tác động của cuộc khai thác thuộc địa lần thứ nhất (1897-1914) của thực dân Pháp?", options: ["Giai cấp tư sản.", "Giai cấp nông dân.", "Giai cấp công nhân.", "Tầng lớp tiểu tư sản."], answer: 2 },
    { type: 'mcq', text: "Câu 6. Phong trào Cần vương (1885-1896) bùng nổ dưới sự lãnh đạo của ai?", options: ["Hoàng Hoa Thám.", "Tôn Thất Thuyết.", "Phan Đình Phùng.", "Nguyễn Thái Học."], answer: 1 },
    { type: 'mcq', text: "Câu 7. Hội Việt Nam Cách mạng Thanh niên (1925) do ai sáng lập?", options: ["Phan Bội Châu.", "Phan Châu Trinh.", "Nguyễn Ái Quốc.", "Trần Phú."], answer: 2 },
    { type: 'mcq', text: "Câu 8. Cương lĩnh chính trị đầu tiên của Đảng Cộng sản Việt Nam (đầu năm 1930) xác định nhiệm vụ của cách mạng Việt Nam là gì?", options: ["Đánh đổ đế quốc chủ nghĩa Pháp và bọn phong kiến.", "Chỉ tập trung đánh đổ giai cấp địa chủ phong kiến.", "Thực hiện cải cách ruộng đất trước rồi mới đánh đế quốc.", "Xây dựng chủ nghĩa xã hội ngay sau khi thành lập Đảng."], answer: 0 },
    { type: 'mcq', text: "Câu 9. Kẻ thù chính của nhân dân Đông Dương được xác định tại Hội nghị Ban Chấp hành Trung ương Đảng (tháng 5-1941) là ai?", options: ["Thực dân Pháp.", "Phát xít Nhật.", "Đế quốc Pháp và phát xít Nhật.", "Chính quyền tay sai."], answer: 2 },
    { type: 'mcq', text: "Câu 10. Sự kiện nào đã trực tiếp dẫn đến sự bùng nổ của cuộc kháng chiến toàn quốc chống thực dân Pháp (tháng 12-1946)?", options: ["Pháp khiêu khích ở Hải Phòng và Lạng Sơn.", "Pháp đánh chiếm Nam Bộ.", "Pháp gửi tối hậu thư đòi ta giao quyền kiểm soát Thủ đô Hà Nội.", "Hội nghị Phông-ten-nơ-blô thất bại."], answer: 2 },
    { type: 'mcq', text: "Câu 11. Chiến dịch phản công lớn đầu tiên của quân và dân ta trong kháng chiến chống Pháp là chiến dịch nào?", options: ["Chiến dịch Việt Bắc thu - đông (1947).", "Chiến dịch Biên giới thu - đông (1950).", "Chiến dịch Tây Bắc (1952).", "Chiến dịch Điện Biên Phủ (1954)."], answer: 0 },
    { type: 'mcq', text: "Câu 12. Việc Mỹ thực hiện Kế hoạch Mác-san (1947) nhằm mục đích chủ yếu nào?", options: ["Giúp đỡ các nước châu Âu phục hồi kinh tế và tập hợp họ vào liên minh chống Liên Xô.", "Biến các nước Tây Âu thành thuộc địa kiểu mới.", "Thúc đẩy sự hội nhập kinh tế toàn cầu.", "Mở rộng ảnh hưởng của Mỹ sang châu Á."], answer: 0 },
    { type: 'mcq', text: "Câu 13. Chiến thắng nào đã làm phá sản hoàn toàn kế hoạch Na-va của thực dân Pháp?", options: ["Cuộc tiến công chiến lược Đông Xuân 1953 - 1954.", "Chiến dịch Điện Biên Phủ (1954).", "Chiến dịch Biên giới thu - đông (1950).", "Chiến dịch Hòa Bình (1951)."], answer: 1 },
    { type: 'mcq', text: "Câu 14. Phong trào Đồng khởi (1959-1960) đã dẫn đến sự ra đời của tổ chức nào?", options: ["Mặt trận Tổ quốc Việt Nam.", "Mặt trận Dân chủ Đông Dương.", "Mặt trận Dân tộc giải phóng miền Nam Việt Nam.", "Chính phủ Cách mạng lâm thời Cộng hòa miền Nam Việt Nam."], answer: 2 },
    { type: 'mcq', text: "Câu 15. Chiến lược 'Chiến tranh đặc biệt' (1961-1965) của Mỹ được thực hiện chủ yếu bằng lực lượng nào?", options: ["Quân viễn chinh Mỹ.", "Quân đội Sài Gòn.", "Quân đồng minh của Mỹ.", "Lính đánh thuê nước ngoài."], answer: 1 },
    { type: 'mcq', text: "Câu 16. Thắng lợi nào của quân dân miền Nam đã buộc Mỹ phải tuyên bố 'phi Mỹ hóa' chiến tranh xâm lược?", options: ["Phong trào Đồng khởi (1959-1960).", "Cuộc Tổng tiến công và nổi dậy Xuân Mậu Thân (1968).", "Cuộc Tiến công chiến lược (1972).", "Chiến thắng Đường 14 - Phước Long (1975)."], answer: 1 },
    { type: 'mcq', text: "Câu 17. Hiệp định Pa-ri (1973) có điều khoản nào mang tính quyết định đối với sự phát triển của cách mạng miền Nam Việt Nam?", options: ["Mỹ viện trợ kinh tế cho Việt Nam.", "Mỹ phải rút hết quân viễn chinh và quân đồng minh về nước.", "Hai bên trao trả tù binh.", "Thành lập Hội đồng quốc gia hòa giải dân tộc."], answer: 1 },
    { type: 'mcq', text: "Câu 18. Chiến dịch mở màn cho cuộc Tổng tiến công và nổi dậy Xuân 1975 là?", options: ["Chiến dịch Tây Nguyên.", "Chiến dịch Huế - Đà Nẵng.", "Chiến dịch Hồ Chí Minh.", "Chiến dịch Phước Long."], answer: 0 },
    { type: 'mcq', text: "Câu 19. Sự kiện nào đánh dấu Việt Nam đã hoàn thành thống nhất đất nước về mặt nhà nước sau năm 1975?", options: ["Đại thắng mùa Xuân 1975.", "Kì họp thứ nhất Quốc hội khóa VI (1976).", "Hội nghị hiệp thương chính trị thống nhất đất nước (1975).", "Đại hội đại biểu toàn quốc lần thứ IV của Đảng (1976)."], answer: 1 },
    { type: 'mcq', text: "Câu 20. Tại Đại hội VI (1986), Đảng Cộng sản Việt Nam chủ trương đổi mới trước hết trên lĩnh vực nào?", options: ["Chính trị.", "Văn hóa.", "Kinh tế.", "Giáo dục."], answer: 2 },
    { type: 'mcq', text: "Câu 21. Sự kiện nào đánh dấu bước ngoặt trong quan hệ Việt Nam - ASEAN?", options: ["Việt Nam kí Hiệp ước Ba-li (1992).", "Việt Nam chính thức gia nhập ASEAN (1995).", "Việt Nam tham gia AFTA (1995).", "Việt Nam đăng cai Hội nghị cấp cao ASEAN lần thứ 6 (1998)."], answer: 1 },
    { type: 'mcq', text: "Câu 22. Đặc điểm nổi bật của trật tự thế giới sau Chiến tranh lạnh là gì?", options: ["Sự thiết lập trật tự đơn cực do Mỹ làm bá chủ.", "Thế giới chuyển dần sang xu hướng đa cực, nhiều trung tâm.", "Chủ nghĩa xã hội vươn lên nắm vai trò chi phối toàn cầu.", "Sự đối đầu trực tiếp giữa Liên minh châu Âu và Mỹ."], answer: 1 },
    { type: 'mcq', text: "Câu 23. Bài học kinh nghiệm lớn nhất được đ
