/* =========================================================================
   DỮ LIỆU LỊCH SỬ KHỐI 12 - HOÀN THIỆN 10 TEST/CHỦ ĐỀ (10 CÂU/TEST)
   Bản quyền thuộc về số ĐT: 0943.930.787
========================================================================= */

// =========================================================================
// NGÂN HÀNG CÂU HỎI (POOLS)
// =========================================================================

// --- CHỦ ĐỀ 1: THẾ GIỚI SAU CHIẾN TRANH LẠNH & ASEAN ---
const cd1_mcq = [
    { type: 'mcq', text: "Hội nghị I-an-ta (tháng 2/1945) có sự tham gia của nguyên thủ 3 cường quốc nào?", options: ["Anh, Pháp, Mỹ.", "Liên Xô, Mỹ, Anh.", "Liên Xô, Mỹ, Pháp.", "Mỹ, Anh, Trung Quốc."], answer: 1 },
    { type: 'mcq', text: "Theo quyết định của Hội nghị I-an-ta, khu vực nào thuộc phạm vi ảnh hưởng của Liên Xô?", options: ["Tây Âu.", "Đông Nam Á.", "Đông Âu.", "Tây Đức."], answer: 2 },
    { type: 'mcq', text: "Tổ chức Liên hợp quốc chính thức được thành lập vào ngày tháng năm nào?", options: ["24/10/1945.", "25/04/1945.", "26/06/1945.", "02/09/1945."], answer: 0 },
    { type: 'mcq', text: "Cơ quan nào của Liên hợp quốc chịu trách nhiệm chính trong việc duy trì hòa bình và an ninh quốc tế?", options: ["Đại hội đồng.", "Hội đồng Bảo an.", "Ban Thư kí.", "Hội đồng Quản thác."], answer: 1 },
    { type: 'mcq', text: "Đặc trưng lớn nhất của trật tự thế giới được hình thành sau Chiến tranh thế giới thứ hai là gì?", options: ["Sự thống trị của Mỹ.", "Thế giới chia thành hai phe TBCN và XHCN do Mỹ và Liên Xô đứng đầu.", "Sự hình thành thế giới đa cực.", "Sự ra đời của các liên minh kinh tế."], answer: 1 },
    { type: 'mcq', text: "Năm cường quốc có quyền phủ quyết (Veto) tại Hội đồng Bảo an Liên hợp quốc bao gồm:", options: ["Mỹ, Anh, Pháp, Đức, Nhật.", "Nga, Mỹ, Anh, Pháp, Trung Quốc.", "Nga, Mỹ, Nhật, Ấn Độ, Trung Quốc.", "Mỹ, Anh, Pháp, I-ta-li-a, Trung Quốc."], answer: 1 },
    { type: 'mcq', text: "Sự kiện nào đánh dấu sự sụp đổ của Trật tự thế giới hai cực I-an-ta?", options: ["Hiệp định Giơ-ne-vơ (1954).", "Chiến tranh Việt Nam kết thúc (1975).", "Chế độ XHCN ở Liên Xô và Đông Âu sụp đổ (1989-1991).", "Chiến tranh Lạnh kết thúc (1989)."], answer: 2 },
    { type: 'mcq', text: "Sau khi Chiến tranh lạnh kết thúc, trật tự thế giới đang định hình theo xu hướng nào?", options: ["Trật tự đơn cực.", "Trật tự đa cực, nhiều trung tâm.", "Trật tự hai cực kiểu mới.", "Chủ nghĩa đa phương."], answer: 1 },
    { type: 'mcq', text: "Hiện tượng nào nổi lên như một xu thế khách quan, chi phối nền kinh tế toàn cầu từ sau Chiến tranh lạnh?", options: ["Quốc hữu hóa.", "Toàn cầu hóa kinh tế.", "Phân lập thị trường.", "Bảo hộ mậu dịch."], answer: 1 },
    { type: 'mcq', text: "Sức mạnh tổng hợp của một quốc gia trong thế kỉ XXI được đánh giá dựa trên yếu tố cốt lõi nào?", options: ["Sức mạnh quân sự.", "Quy mô dân số.", "Sức mạnh kinh tế, khoa học - công nghệ.", "Diện tích lãnh thổ."], answer: 2 },
    { type: 'mcq', text: "Hiệp hội các quốc gia Đông Nam Á (ASEAN) được thành lập vào năm 1967 tại đâu?", options: ["Gia-các-ta.", "Băng Cốc.", "Ma-ni-la.", "Cua-la Lăm-pơ."], answer: 1 },
    { type: 'mcq', text: "Năm quốc gia sáng lập ASEAN bao gồm:", options: ["Thái Lan, In-đô-nê-xi-a, Ma-lai-xi-a, Phi-líp-pin, Xin-ga-po.", "Thái Lan, Việt Nam, In-đô-nê-xi-a, Phi-líp-pin, Miến Điện.", "Xin-ga-po, Bru-nây, Thái Lan, Ma-lai-xi-a, Phi-líp-pin.", "Việt Nam, Lào, Cam-pu-chia, Thái Lan, Miến Điện."], answer: 0 },
    { type: 'mcq', text: "Văn kiện nào đánh dấu sự ra đời của ASEAN?", options: ["Hiến chương ASEAN.", "Tuyên bố Băng Cốc.", "Hiệp ước Ba-li.", "Tuyên bố tầm nhìn ASEAN."], answer: 1 },
    { type: 'mcq', text: "Nguyên tắc cốt lõi nào của ASEAN được khẳng định trong Hiệp ước Ba-li?", options: ["Sử dụng vũ lực để giải quyết tranh chấp.", "Can thiệp sâu vào công việc nội bộ.", "Tôn trọng độc lập, chủ quyền và không can thiệp vào công việc nội bộ.", "Quyết định theo đa số."], answer: 2 },
    { type: 'mcq', text: "Việt Nam chính thức gia nhập ASEAN vào năm nào?", options: ["1992.", "1995.", "1997.", "1999."], answer: 1 },
    { type: 'mcq', text: "Sự kiện nào đánh dấu ASEAN bao gồm trọn vẹn 10 quốc gia Đông Nam Á?", options: ["Việt Nam gia nhập (1995).", "Lào và Miến Điện gia nhập (1997).", "Cam-pu-chia gia nhập (1999).", "Đông Ti-mo trở thành quan sát viên."], answer: 2 },
    { type: 'mcq', text: "Cộng đồng ASEAN (AC) chính thức được thành lập vào ngày tháng năm nào?", options: ["31/12/2015.", "8/8/2007.", "1/1/2000.", "28/7/1995."], answer: 0 },
    { type: 'mcq', text: "Đâu KHÔNG phải là một trụ cột của Cộng đồng ASEAN?", options: ["Cộng đồng Chính trị - An ninh (APSC).", "Cộng đồng Kinh tế (AEC).", "Cộng đồng Văn hóa - Xã hội (ASCC).", "Cộng đồng Quân sự - Phòng thủ (AMDC)."], answer: 3 },
    { type: 'mcq', text: "Khẩu hiệu (Motto) của ASEAN là gì?", options: ["Một Tầm nhìn, Một Bản sắc, Một Cộng đồng.", "Hòa bình, Độc lập, Tự do.", "Đoàn kết là sức mạnh.", "Đa dạng trong thống nhất."], answer: 0 },
    { type: 'mcq', text: "Trong lĩnh vực an ninh Biển Đông, Việt Nam đã thúc đẩy mạnh mẽ việc kí kết văn kiện nào cùng ASEAN?", options: ["Hiệp ước phòng thủ quân sự chung.", "Tuyên bố ứng xử các bên ở Biển Đông (DOC).", "Hiệp định cấm thử vũ khí hạt nhân.", "Hiệp ước mậu dịch tự do."], answer: 1 },
    { type: 'mcq', text: "Hội nghị I-an-ta quyết định tiêu diệt tận gốc chủ nghĩa nào?", options: ["Chủ nghĩa tư bản.", "Chủ nghĩa phát xít.", "Chủ nghĩa cộng sản.", "Chủ nghĩa thực dân."], answer: 1 },
    { type: 'mcq', text: "Theo Hội nghị I-an-ta, quân đội nước nào sẽ chiếm đóng Nhật Bản?", options: ["Liên Xô.", "Anh.", "Pháp.", "Mỹ."], answer: 3 },
    { type: 'mcq', text: "Trụ sở chính của Liên hợp quốc hiện nay đặt tại đâu?", options: ["Luân Đôn (Anh).", "Gia-các-ta (In-đô-nê-xi-a).", "Niu Y-oóc (Mỹ).", "Giơ-ne-vơ (Thụy Sĩ)."], answer: 2 },
    { type: 'mcq', text: "Tổng Thư kí Liên hợp quốc là người đứng đầu cơ quan nào?", options: ["Hội đồng Bảo an.", "Đại hội đồng.", "Ban Thư kí.", "Tòa án Quốc tế."], answer: 2 },
    { type: 'mcq', text: "Khối liên minh quân sự lớn nhất của phe TBCN trong Chiến tranh lạnh là?", options: ["NATO.", "Vác-sa-va.", "SEATO.", "CENTO."], answer: 0 },
    { type: 'mcq', text: "Khối liên minh quân sự của phe XHCN trong Chiến tranh lạnh là?", options: ["NATO.", "Vác-sa-va.", "SEATO.", "CENTO."], answer: 1 },
    { type: 'mcq', text: "Cuộc chạy đua vũ trang giữa Mỹ và Liên Xô chủ yếu tập trung vào loại vũ khí nào?", options: ["Vũ khí sinh học.", "Vũ khí hóa học.", "Vũ khí hạt nhân.", "Vũ khí thông thường."], answer: 2 },
    { type: 'mcq', text: "G20 là diễn đàn kinh tế gồm bao nhiêu nền kinh tế lớn nhất thế giới?", options: ["10.", "15.", "20.", "25."], answer: 2 },
    { type: 'mcq', text: "Tổ chức thương mại toàn cầu lớn nhất hiện nay là?", options: ["IMF.", "WB.", "WTO.", "EU."], answer: 2 },
    { type: 'mcq', text: "Liên minh châu Âu (EU) sử dụng đồng tiền chung nào?", options: ["Bảng Anh.", "Đô la Mỹ.", "Euro.", "Yên Nhật."], answer: 2 },
    { type: 'mcq', text: "Quốc gia nào ở Đông Nam Á gia nhập ASEAN năm 1984?", options: ["Việt Nam.", "Bru-nây.", "Lào.", "Cam-pu-chia."], answer: 1 },
    { type: 'mcq', text: "Mục tiêu chính của Cộng đồng Kinh tế ASEAN (AEC) là tạo ra một:", options: ["Khối phòng thủ chung.", "Thị trường và cơ sở sản xuất thống nhất.", "Nhà nước Đông Nam Á.", "Đồng tiền chung duy nhất."], answer: 1 },
    { type: 'mcq', text: "Năm 2020, Việt Nam đảm nhận vai trò gì trong ASEAN?", options: ["Tổng Thư kí ASEAN.", "Chủ tịch luân phiên ASEAN.", "Chỉ huy lực lượng gìn giữ hòa bình.", "Đăng cai Đại hội thể thao Đông Nam Á."], answer: 1 },
    { type: 'mcq', text: "Cộng đồng Văn hóa - Xã hội ASEAN (ASCC) lấy yếu tố nào làm trung tâm?", options: ["Kinh tế.", "Quân sự.", "Con người.", "Chính trị."], answer: 2 },
    { type: 'mcq', text: "Đông Ti-mo nộp đơn xin gia nhập ASEAN vào năm nào?", options: ["2002.", "2011.", "2015.", "2020."], answer: 1 },
    { type: 'mcq', text: "Một trong những thách thức an ninh phi truyền thống toàn cầu hiện nay là?", options: ["Chiến tranh hạt nhân.", "Biến đổi khí hậu và dịch bệnh.", "Chiến tranh lạnh.", "Xâm lược lãnh thổ bằng quân sự."], answer: 1 },
    { type: 'mcq', text: "Diễn đàn khu vực ASEAN (ARF) tập trung vào lĩnh vực hợp tác nào?", options: ["Kinh tế.", "Giáo dục.", "An ninh chính trị.", "Văn hóa."], answer: 2 },
    { type: 'mcq', text: "AFTA là khu vực mậu dịch tự do của tổ chức nào?", options: ["EU.", "ASEAN.", "NAFTA.", "MERCOSUR."], answer: 1 },
    { type: 'mcq', text: "Chiến tranh lạnh chấm dứt đã tạo điều kiện thuận lợi cho xu thế nào phát triển?", options: ["Chạy đua vũ trang.", "Hòa bình, hợp tác và đối thoại.", "Chiến tranh hạt nhân.", "Chủ nghĩa thực dân."], answer: 1 },
    { type: 'mcq', text: "Quốc gia nào hiện nay là nền kinh tế lớn thứ hai thế giới?", options: ["Nhật Bản.", "Đức.", "Trung Quốc.", "Ấn Độ."], answer: 2 }
];

const cd1_tf = [
    { type: 'tf', text: "Về Hội nghị I-an-ta (1945):", options: [{ text: "a) Diễn ra khi Chiến tranh thế giới thứ hai bước vào giai đoạn kết thúc.", answer: true }, { text: "b) Thống nhất mục tiêu chung là tiêu diệt tận gốc chủ nghĩa phát xít.", answer: true }, { text: "c) Thỏa thuận phân chia phạm vi ảnh hưởng ở châu Phi và Mỹ La-tinh.", answer: false }, { text: "d) Quyết định của Hội nghị đã tạo khuôn khổ cho Trật tự thế giới mới.", answer: true }]},
    { type: 'tf', text: "Về tổ chức Liên hợp quốc:", options: [{ text: "a) Được thành lập nhằm mục đích duy trì hòa bình thế giới.", answer: true }, { text: "b) Nguyên tắc cốt lõi là bình đẳng chủ quyền giữa các quốc gia.", answer: true }, { text: "c) Có quyền can thiệp vũ trang vào công việc nội bộ của mọi quốc gia.", answer: false }, { text: "d) Việt Nam chính thức trở thành thành viên vào năm 1977.", answer: true }]},
    { type: 'tf', text: "Về Trật tự hai cực I-an-ta:", options: [{ text: "a) Hình thành sự đối đầu gay gắt giữa hai phe TBCN và XHCN.", answer: true }, { text: "b) Dẫn đến cuộc Chiến tranh lạnh kéo dài hơn 4 thập kỉ.", answer: true }, { text: "c) Mọi quốc gia đều bị ép gia nhập khối NATO hoặc Vác-sa-va.", answer: false }, { text: "d) Sự tan rã của Liên Xô đánh dấu sự chấm dứt của Trật tự này.", answer: true }]},
    { type: 'tf', text: "Về sự kết thúc Chiến tranh lạnh:", options: [{ text: "a) Tháng 12/1989, Mỹ và Liên Xô tuyên bố chấm dứt Chiến tranh lạnh.", answer: true }, { text: "b) Sự kiện này dẫn đến việc giải thể ngay lập tức khối NATO.", answer: false }, { text: "c) Giúp giảm căng thẳng quốc tế, giải quyết hòa bình các xung đột.", answer: true }, { text: "d) Mỹ đã thiết lập được thế giới đơn cực tuyệt đối ngay sau đó.", answer: false }]},
    { type: 'tf', text: "Về xu thế đa cực trong quan hệ quốc tế:", options: [{ text: "a) Là một quá trình khách quan do sự phát triển không đều về kinh tế.", answer: true }, { text: "b) Mỹ dù là siêu cường nhưng không thể một mình chi phối thế giới.", answer: true }, { text: "c) Các trung tâm như EU, Nhật Bản, Trung Quốc ngày càng vươn lên.", answer: true }, { text: "d) Trong thế giới đa cực, Liên hợp quốc hoàn toàn mất đi vai trò.", answer: false }]},
    { type: 'tf', text: "Về sự trỗi dậy của Trung Quốc:", options: [{ text: "a) Nhờ Cải cách mở cửa, Trung Quốc vươn lên thành nền kinh tế lớn thứ 2.", answer: true }, { text: "b) Trung Quốc đã gia nhập WTO và hội nhập sâu rộng vào kinh tế toàn cầu.", answer: true }, { text: "c) Sự vươn lên của Trung Quốc không có ảnh hưởng gì đến cục diện thế giới.", answer: false }, { text: "d) Trung Quốc đang cạnh tranh ảnh hưởng quyết liệt với Mỹ.", answer: true }]},
    { type: 'tf', text: "Về sự ra đời của ASEAN (1967):", options: [{ text: "a) Các nước ĐNÁ có nhu cầu hợp tác để phát triển kinh tế sau khi độc lập.", answer: true }, { text: "b) Thành lập dưới sự chỉ đạo trực tiếp của Liên hợp quốc.", answer: false }, { text: "c) Tuyên bố Băng Cốc là văn kiện nền tảng thành lập Hiệp hội.", answer: true }, { text: "d) Nhằm hạn chế sự can thiệp của các cường quốc bên ngoài.", answer: true }]},
    { type: 'tf', text: "Về Hiệp ước Ba-li (1976):", options: [{ text: "a) Đánh dấu bước khởi sắc của ASEAN.", answer: true }, { text: "b) Đề ra nguyên tắc giải quyết các tranh chấp bằng hòa bình.", answer: true }, { text: "c) Yêu cầu xóa bỏ biên giới quốc gia giữa các nước thành viên.", answer: false }, { text: "d) Khẳng định nguyên tắc đồng thuận và không can thiệp nội bộ.", answer: true }]},
    { type: 'tf', text: "Về Cộng đồng ASEAN (AC):", options: [{ text: "a) Thành lập là bước ngoặt lịch sử sau gần 50 năm.", answer: true }, { text: "b) Đánh dấu mức độ liên kết chặt chẽ nhất của các nước Đông Nam Á.", answer: true }, { text: "c) AC ra đời làm mất đi chủ quyền quốc gia của các nước thành viên.", answer: false }, { text: "d) Phản ánh nhu cầu hợp tác để đối phó với thách thức toàn cầu.", answer: true }]},
    { type: 'tf', text: "Về đóng góp của Việt Nam trong ASEAN:", options: [{ text: "a) Việt Nam luôn là thành viên chủ động, tích cực và có trách nhiệm.", answer: true }, { text: "b) Đóng góp lớn nhất là viện trợ tài chính vô hoàn lại cho khối.", answer: false }, { text: "c) Góp phần củng cố đoàn kết nội khối và vai trò trung tâm của ASEAN.", answer: true }, { text: "d) Đã đăng cai tổ chức thành công nhiều Hội nghị cấp cao ASEAN.", answer: true }]},
    { type: 'tf', text: "Về xu thế toàn cầu hóa kinh tế:", options: [{ text: "a) Thúc đẩy lực lượng sản xuất ở mức độ cao.", answer: true }, { text: "b) Chỉ mang lại lợi ích cho các nước đang phát triển.", answer: false }, { text: "c) Gia tăng sự phụ thuộc lẫn nhau giữa các quốc gia.", answer: true }, { text: "d) Làm gia tăng khoảng cách giàu nghèo trên toàn cầu.", answer: true }]},
    { type: 'tf', text: "Về thách thức an ninh toàn cầu:", options: [{ text: "a) Khủng bố quốc tế là mối đe dọa lớn đối với an ninh thế giới.", answer: true }, { text: "b) Biến đổi khí hậu không được coi là vấn đề an ninh phi truyền thống.", answer: false }, { text: "c) Đòi hỏi sự hợp tác của toàn bộ cộng đồng quốc tế.", answer: true }, { text: "d) Vụ 11/9/2001 đã làm thay đổi chính sách đối ngoại của Mỹ.", answer: true }]},
    { type: 'tf', text: "Về Cộng đồng Kinh tế ASEAN (AEC):", options: [{ text: "a) AEC tạo ra thị trường chung với hơn 600 triệu dân.", answer: true }, { text: "b) Cho phép lao động phổ thông di chuyển tự do không giới hạn.", answer: false }, { text: "c) Tăng cường sức cạnh tranh của ASEAN trên thị trường toàn cầu.", answer: true }, { text: "d) Tự do luân chuyển hàng hóa, dịch vụ và vốn đầu tư.", answer: true }]},
    { type: 'tf', text: "Về Cộng đồng Chính trị - An ninh ASEAN (APSC):", options: [{ text: "a) Biến ASEAN thành một khối liên minh quân sự như NATO.", answer: false }, { text: "b) Nhằm xây dựng môi trường hòa bình, ổn định.", answer: true }, { text: "c) Cam kết giải quyết tranh chấp bằng biện pháp hòa bình.", answer: true }, { text: "d) Tôn trọng tính trung tâm của ASEAN trong khu vực.", answer: true }]},
    { type: 'tf', text: "Về quá trình phát triển ASEAN 10:", options: [ { text: "a) Quá trình mở rộng diễn ra nhanh chóng ngay trong năm 1968.", answer: false }, { text: "b) Giải quyết xong vấn đề Cam-pu-chia tháo gỡ rào cản lớn cho mở rộng.", answer: true }, { text: "c) Từ 'ASEAN 5' lên 'ASEAN 10' biến khu vực từ đối đầu sang đối thoại.", answer: true }, { text: "d) Cam-pu-chia là nước gia nhập cuối cùng để hoàn thiện ASEAN 10.", answer: true }]},
    { type: 'tf', text: "Về Hiến chương ASEAN (2007):", options: [{ text: "a) Là văn kiện pháp lý tạo khung cho Cộng đồng ASEAN.", answer: true }, { text: "b) Chuyển ASEAN thành tổ chức có tư cách pháp nhân.", answer: true }, { text: "c) Loại bỏ quyền biểu quyết của các nước nhỏ.", answer: false }, { text: "d) Thể hiện quyết tâm hội nhập sâu rộng.", answer: true }]},
    { type: 'tf', text: "Về Tuyên bố ứng xử ở Biển Đông (DOC):", options: [{ text: "a) Được ASEAN và Trung Quốc kí kết năm 2002.", answer: true }, { text: "b) Có chế tài xử phạt quân sự đối với nước vi phạm.", answer: false }, { text: "c) Cam kết giải quyết tranh chấp bằng hòa bình, tôn trọng luật quốc tế.", answer: true }, { text: "d) Việt Nam có vai trò tích cực thúc đẩy kí kết DOC.", answer: true }]},
    { type: 'tf', text: "Về Hội đồng Bảo an Liên hợp quốc:", options: [{ text: "a) Là cơ quan có quyền áp dụng biện pháp cưỡng chế, kể cả vũ lực.", answer: true }, { text: "b) Mọi quyết định phải được tất cả 193 nước thành viên thông qua.", answer: false }, { text: "c) Áp dụng nguyên tắc nhất trí giữa 5 Ủy viên thường trực.", answer: true }, { text: "d) Có 10 Ủy viên không thường trực được bầu luân phiên.", answer: true }]},
    { type: 'tf', text: "Về G20:", options: [{ text: "a) Gồm các nền kinh tế phát triển và mới nổi lớn nhất thế giới.", answer: true }, { text: "b) Nhằm thay thế hoàn toàn Liên hợp quốc.", answer: false }, { text: "c) Phản ánh sự dịch chuyển quyền lực kinh tế về phía các nước đang phát triển.", answer: true }, { text: "d) Việt Nam hiện là thành viên thường trực của G20.", answer: false }]},
    { type: 'tf', text: "Về xu thế điều chỉnh chiến lược của các nước lớn:", options: [{ text: "a) Lấy phát triển kinh tế làm trọng tâm.", answer: true }, { text: "b) Ưu tiên số một là chạy đua vũ trang hạt nhân.", answer: false }, { text: "c) Tăng cường đối thoại, thỏa hiệp, tránh xung đột trực tiếp.", answer: true }, { text: "d) Cạnh tranh về khoa học - công nghệ diễn ra khốc liệt.", answer: true }]}
];

// --- CHỦ ĐỀ 2: CÁCH MẠNG GPDT & BẢO VỆ TỔ QUỐC (1945-1975) ---
const cd2_mcq = [
    { type: 'mcq', text: "Hội nghị Trung ương 8 (5/1941) xác định nhiệm vụ hàng đầu của cách mạng Việt Nam là gì?", options: ["Giải phóng giai cấp công nhân.", "Đánh đổ phong kiến, chia ruộng đất.", "Giải phóng dân tộc.", "Xây dựng chủ nghĩa xã hội."], answer: 2 },
    { type: 'mcq', text: "Sự kiện nào tạo ra 'thời cơ ngàn năm có một' cho Cách mạng tháng Tám (1945)?", options: ["Phát xít Đức đầu hàng Đồng minh.", "Pháp quay trở lại xâm lược Đông Dương.", "Nhật Bản đảo chính Pháp.", "Phát xít Nhật đầu hàng Đồng minh không điều kiện."], answer: 3 },
    { type: 'mcq', text: "Khởi nghĩa giành chính quyền ở Hà Nội thắng lợi vào ngày nào?", options: ["19/8/1945.", "23/8/1945.", "25/8/1945.", "2/9/1945."], answer: 0 },
    { type: 'mcq', text: "Khó khăn lớn nhất đe dọa sự tồn vong của VNDCCH ngay sau Cách mạng tháng Tám là gì?", options: ["Nạn đói.", "Nạn dốt.", "Ngân quỹ trống rỗng.", "Thù trong giặc ngoài (ngoại xâm và nội phản)."], answer: 3 },
    { type: 'mcq', text: "Đường lối kháng chiến chống Pháp của Đảng được tóm tắt trong 4 đặc điểm nào?", options: ["Nhanh chóng, bất ngờ, triệt để, toàn diện.", "Toàn dân, toàn diện, trường kì, tự lực cánh sinh.", "Liên minh, hiện đại, thần tốc, táo bạo.", "Du kích, phòng ngự, phản công, chiến thắng."], answer: 1 },
    { type: 'mcq', text: "Chiến dịch nào đã làm thất bại chiến lược 'đánh nhanh thắng nhanh' của Pháp?", options: ["Việt Bắc thu - đông (1947).", "Biên giới thu - đông (1950).", "Tây Bắc (1952).", "Điện Biên Phủ (1954)."], answer: 0 },
    { type: 'mcq', text: "Chiến thắng Biên giới thu - đông (1950) có ý nghĩa chiến lược như thế nào?", options: ["Giải phóng hoàn toàn Hà Nội.", "Đánh bại Kế hoạch Na-va.", "Quân ta giành quyền chủ động trên chiến trường chính Bắc Bộ.", "Buộc Pháp kí Hiệp định Pa-ri."], answer: 2 },
    { type: 'mcq', text: "Đại hội đại biểu toàn quốc lần thứ II (2/1951) đã quyết định đổi tên Đảng thành gì?", options: ["Đảng Cộng sản Đông Dương.", "Đảng Lao động Việt Nam.", "Đảng Cộng sản Việt Nam.", "Đảng Dân chủ Việt Nam."], answer: 1 },
    { type: 'mcq', text: "Điểm then chốt của Kế hoạch Na-va (1953) của thực dân Pháp là gì?", options: ["Tập trung binh lực, xây dựng đội quân cơ động chiến lược mạnh.", "Xây dựng phòng tuyến boong-ke.", "Đánh phá miền Bắc bằng không quân.", "Cầu viện quân đội Mỹ trực tiếp tham chiến."], answer: 0 },
    { type: 'mcq', text: "Hiệp định Giơ-ne-vơ (1954) quy định vĩ tuyến nào là giới tuyến quân sự tạm thời?", options: ["Vĩ tuyến 13.", "Vĩ tuyến 16.", "Vĩ tuyến 17.", "Vĩ tuyến 20."], answer: 2 },
    { type: 'mcq', text: "Nhiệm vụ của cách mạng miền Nam sau năm 1954 là gì?", options: ["Tiến lên chủ nghĩa xã hội.", "Tiếp tục cách mạng dân tộc dân chủ nhân dân.", "Phát triển tư bản chủ nghĩa.", "Quản thác quốc tế."], answer: 1 },
    { type: 'mcq', text: "Phong trào 'Đồng khởi' (1959-1960) bùng nổ mạnh mẽ nhất từ tỉnh nào?", options: ["Quảng Nam.", "Tây Ninh.", "Bến Tre.", "Trà Vinh."], answer: 2 },
    { type: 'mcq', text: "Chiến lược 'Chiến tranh đặc biệt' (1961-1965) được tiến hành bằng lực lượng chủ yếu nào?", options: ["Quân viễn chinh Mỹ.", "Quân đội đồng minh Mỹ.", "Quân đội Sài Gòn dưới sự chỉ huy của cố vấn Mỹ.", "Lính đánh thuê LHQ."], answer: 2 },
    { type: 'mcq', text: "Xương sống của chiến lược 'Chiến tranh đặc biệt' là gì?", options: ["Quân đội Mỹ.", "Ấp chiến lược.", "Vũ khí hiện đại.", "Không quân Mỹ."], answer: 1 },
    { type: 'mcq', text: "Điểm mới của chiến lược 'Chiến tranh cục bộ' (1965-1968) so với 'Chiến tranh đặc biệt' là gì?", options: ["Sử dụng cố vấn quân sự.", "Sử dụng vũ khí Mỹ.", "Mở rộng chiến tranh ra Đông Dương.", "Đưa quân viễn chinh Mỹ trực tiếp tham chiến."], answer: 3 },
    { type: 'mcq', text: "Sự kiện nào buộc Mỹ tuyên bố 'phi Mỹ hóa' chiến tranh và ngồi vào bàn đàm phán Pa-ri?", options: ["Phong trào Đồng khởi.", "Chiến thắng Vạn Tường.", "Cuộc Tổng tiến công và nổi dậy Xuân Mậu Thân (1968).", "Trận Điện Biên Phủ trên không."], answer: 2 },
    { type: 'mcq', text: "Bản chất của chiến lược 'Việt Nam hóa chiến tranh' (1969-1973) là gì?", options: ["Rút toàn bộ quân Mỹ.", "Dùng người Việt đánh người Việt bằng vũ khí Mỹ.", "Lôi kéo các nước châu Á tham chiến.", "Chia Việt Nam thành nhiều quốc gia."], answer: 1 },
    { type: 'mcq', text: "Trận 'Điện Biên Phủ trên không' (1972) đập tan cuộc tập kích bằng vũ khí gì của Mỹ?", options: ["Máy bay tiêm kích.", "Máy bay B-52.", "Tên lửa hành trình.", "Vũ khí sinh học."], answer: 1 },
    { type: 'mcq', text: "Chiến dịch mở màn cho cuộc Tổng tiến công Xuân 1975 là?", options: ["Tây Nguyên.", "Huế - Đà Nẵng.", "Hồ Chí Minh.", "Phước Long."], answer: 0 },
    { type: 'mcq', text: "Sự kiện nào đánh dấu Việt Nam đã hoàn thành thống nhất đất nước về mặt nhà nước sau 1975?", options: ["Đại thắng mùa Xuân 1975.", "Kì họp thứ nhất Quốc hội khóa VI (1976).", "Hội nghị hiệp thương chính trị (1975).", "Đại hội Đảng lần thứ IV (1976)."], answer: 1 },
    { type: 'mcq', text: "Chỉ thị 'Nhật - Pháp bắn nhau và hành động của chúng ta' xác định kẻ thù chính là ai?", options: ["Thực dân Pháp.", "Phát xít Nhật.", "Quân Đồng minh.", "Pháp và Nhật."], answer: 1 },
    { type: 'mcq', text: "Đội Việt Nam Tuyên truyền Giải phóng quân được thành lập vào ngày tháng năm nào?", options: ["22/12/1944.", "15/5/1945.", "19/8/1945.", "2/9/1945."], answer: 0 },
    { type: 'mcq', text: "Quốc dân Đại hội Tân Trào (16/8/1945) đã quyết định điều gì?", options: ["Đổi tên Đảng.", "Phát động kháng chiến chống Pháp.", "Tán thành Tổng khởi nghĩa, lập Ủy ban Dân tộc giải phóng.", "Thành lập Quân đội Nhân dân."], answer: 2 },
    { type: 'mcq', text: "Hình thái của Cách mạng tháng Tám năm 1945 là gì?", options: ["Tổng bãi công.", "Khởi nghĩa từng phần tiến lên Tổng khởi nghĩa.", "Đấu tranh nghị trường.", "Chiến tranh quy mô lớn."], answer: 1 },
    { type: 'mcq', text: "Lời kêu gọi toàn quốc kháng chiến được Chủ tịch Hồ Chí Minh ra lời vào ngày nào?", options: ["2/9/1945.", "19/12/1946.", "20/12/1946.", "22/12/1946."], answer: 1 },
    { type: 'mcq', text: "Hiệp định Sơ bộ (6/3/1946) ta kí với thế lực nào?", options: ["Tưởng Giới Thạch.", "Anh.", "Pháp.", "Nhật."], answer: 2 },
    { type: 'mcq', text: "Trận đánh nào được coi là 'cái nôi' của nghệ thuật chiến tranh du kích trong chống Pháp?", options: ["Đông Khê.", "Tây Bắc.", "Các trận đánh sau lưng địch.", "Điện Biên Phủ."], answer: 2 },
    { type: 'mcq', text: "Thắng lợi của chiến dịch Điện Biên Phủ (1954) mang ý nghĩa lớn nhất là gì?", options: ["Giải phóng miền Nam.", "Đập tan Kế hoạch Na-va, tạo thế mạnh trên bàn đàm phán Giơ-ne-vơ.", "Làm sụp đổ chính quyền Sài Gòn.", "Kết thúc ách Bắc thuộc."], answer: 1 },
    { type: 'mcq', text: "Nghị quyết 15 (1/1959) của Trung ương Đảng đã vạch ra con đường cách mạng miền Nam là gì?", options: ["Đấu tranh hòa bình.", "Đấu tranh nghị trường.", "Khởi nghĩa vũ trang (sử dụng bạo lực cách mạng).", "Chờ đợi bầu cử."], answer: 2 },
    { type: 'mcq', text: "Thắng lợi của chiến dịch Hồ Chí Minh (1975) đã giải phóng hoàn toàn thành phố nào?", options: ["Huế.", "Đà Nẵng.", "Sài Gòn.", "Buôn Ma Thuột."], answer: 2 },
    { type: 'mcq', text: "Văn kiện nào khẳng định nước Việt Nam Dân chủ Cộng hòa ra đời?", options: ["Bình Ngô Đại cáo.", "Tuyên ngôn Độc lập (2/9/1945).", "Hiến pháp 1946.", "Hiệp định Giơ-ne-vơ."], answer: 1 },
    { type: 'mcq', text: "Ai là người trực tiếp chỉ huy Chiến dịch Điện Biên Phủ (1954)?", options: ["Phạm Văn Đồng.", "Võ Nguyên Giáp.", "Nguyễn Chí Thanh.", "Lê Duẩn."], answer: 1 },
    { type: 'mcq', text: "Tuyến đường Hồ Chí Minh trên bộ (Đường Trường Sơn) được mở vào năm nào?", options: ["1954.", "1959.", "1965.", "1968."], answer: 1 },
    { type: 'mcq', text: "Chiến thắng Ấp Bắc (1/1963) chứng tỏ quân dân miền Nam có khả năng đánh bại chiến lược nào?", options: ["Chiến tranh cục bộ.", "Việt Nam hóa chiến tranh.", "Chiến tranh đặc biệt.", "Chiến tranh đơn phương."], answer: 2 },
    { type: 'mcq', text: "Chiến thắng Vạn Tường (8/1965) mở đầu cao trào gì ở miền Nam?", options: ["Thi đua Ấp Bắc, giết giặc lập công.", "Tìm Mỹ mà đánh, lùng ngụy mà diệt.", "Đồng khởi.", "Diệt ác phá kìm."], answer: 1 },
    { type: 'mcq', text: "Mỹ tiến hành cuộc chiến tranh phá hoại miền Bắc lần thứ nhất (1965-1968) nhằm mục đích gì?", options: ["Chiếm đóng miền Bắc.", "Ngăn chặn sự chi viện của miền Bắc cho miền Nam.", "Thử nghiệm vũ khí.", "Mở rộng lãnh thổ."], answer: 1 },
    { type: 'mcq', text: "Trận then chốt mở màn chiến dịch Tây Nguyên (3/1975) diễn ra ở đâu?", options: ["Pleiku.", "Kon Tum.", "Buôn Ma Thuột.", "Gia Nghĩa."], answer: 2 },
    { type: 'mcq', text: "Tỉnh cuối cùng ở miền Nam được giải phóng trong năm 1975 là?", options: ["Đồng Nai.", "Bà Rịa.", "Châu Đốc.", "Kiên Giang (Phú Quốc)."], answer: 3 },
    { type: 'mcq', text: "Mặt trận Dân tộc giải phóng miền Nam Việt Nam ra đời vào năm nào?", options: ["1954.", "1960.", "1965.", "1968."], answer: 1 },
    { type: 'mcq', text: "Yếu tố quyết định nhất đến thắng lợi của cuộc kháng chiến chống Mỹ là gì?", options: ["Viện trợ quốc tế.", "Địa hình hiểm trở.", "Sự lãnh đạo đúng đắn, sáng suốt của Đảng.", "Sự suy yếu của nước Mỹ."], answer: 2 }
];

const cd2_tf = [
    { type: 'tf', text: "Về Hội nghị Trung ương 8 (5/1941):", options: [{ text: "a) Đánh dấu sự chuyển hướng chỉ đạo chiến lược của Đảng.", answer: true }, { text: "b) Đặt nhiệm vụ giải phóng dân tộc lên hàng đầu.", answer: true }, { text: "c) Quyết định lập Mặt trận Liên Việt.", answer: false }, { text: "d) Giải quyết vấn đề dân tộc trong khuôn khổ từng nước Đông Dương.", answer: true }]},
    { type: 'tf', text: "Về thời cơ của Cách mạng tháng Tám:", options: [{ text: "a) Thời cơ khách quan xuất hiện khi Nhật đầu hàng Đồng minh.", answer: true }, { text: "b) Thời cơ tồn tại rất lâu dài, đến hết 1945.", answer: false }, { text: "c) Chín muồi khi quân Đồng minh chưa kịp kéo vào Đông Dương.", answer: true }, { text: "d) Đảng ta chớp đúng 'thời cơ ngàn năm có một' để phát lệnh Tổng khởi nghĩa.", answer: true }]},
    { type: 'tf', text: "Về diễn biến Tổng khởi nghĩa tháng Tám:", options: [{ text: "a) Diễn ra nhanh chóng, thắng lợi trong 15 ngày.", answer: true }, { text: "b) Vũ trang đóng vai trò quyết định, chính trị là xung kích.", answer: false }, { text: "c) Thắng lợi ở Hà Nội, Huế, Sài Gòn quyết định cục diện cả nước.", answer: true }, { text: "d) Ngày 30/8/1945, vua Bảo Đại thoái vị.", answer: true }]},
    { type: 'tf', text: "Về Tuyên ngôn Độc lập (2/9/1945):", options: [{ text: "a) Khẳng định quyền độc lập của dân tộc trước thế giới.", answer: true }, { text: "b) Khai sinh ra nước Việt Nam Dân chủ Cộng hòa.", answer: true }, { text: "c) Tuyên bố gia nhập Liên minh phương Tây.", answer: false }, { text: "d) Thể hiện lập trường kiên quyết bảo vệ nền độc lập.", answer: true }]},
    { type: 'tf', text: "Về tình hình sau Cách mạng tháng Tám:", options: [{ text: "a) Đất nước ở thế 'ngàn cân treo sợi tóc'.", answer: true }, { text: "b) 20 vạn quân Tưởng kéo vào miền Bắc, quân Anh vào miền Nam.", answer: true }, { text: "c) Liên hợp quốc cử quân đội bảo vệ Việt Nam.", answer: false }, { text: "d) Chính quyền còn non trẻ, thiếu thốn kinh nghiệm và tài chính.", answer: true }]},
    { type: 'tf', text: "Về Lời kêu gọi toàn quốc kháng chiến (1946):", options: [{ text: "a) Do Chủ tịch Hồ Chí Minh soạn thảo.", answer: true }, { text: "b) Khẳng định quyết tâm thà hi sinh tất cả chứ nhất định không chịu mất nước.", answer: true }, { text: "c) Kêu gọi quân Đồng minh can thiệp.", answer: false }, { text: "d) Là lời hịch cứu quốc phát động toàn dân đánh giặc.", answer: true }]},
    { type: 'tf', text: "Về Chiến dịch Điện Biên Phủ (1954):", options: [{ text: "a) Thay đổi phương châm sang 'đánh chắc, tiến chắc'.", answer: true }, { text: "b) Kéo dài 56 ngày đêm.", answer: true }, { text: "c) Mỹ dùng bom nguyên tử để giải cứu quân Pháp.", answer: false }, { text: "d) Quyết định cục diện đàm phán tại Giơ-ne-vơ.", answer: true }]},
    { type: 'tf', text: "Về Hiệp định Giơ-ne-vơ (1954):", options: [{ text: "a) Các nước công nhận các quyền dân tộc cơ bản của 3 nước Đông Dương.", answer: true }, { text: "b) Quy định ngừng bắn, tập kết chuyển quân theo khu vực.", answer: true }, { text: "c) Tổ chức hiệp thương tổng tuyển cử vào năm 1956.", answer: true }, { text: "d) Mỹ cam kết hỗ trợ tái thiết miền Bắc.", answer: false }]},
    { type: 'tf', text: "Về tình hình Việt Nam sau Hiệp định Giơ-ne-vơ:", options: [{ text: "a) Bị chia cắt làm hai miền với hai chế độ chính trị khác nhau.", answer: true }, { text: "b) Miền Bắc giải phóng, quá độ lên chủ nghĩa xã hội.", answer: true }, { text: "c) Mỹ tôn trọng Hiệp định, không can thiệp miền Nam.", answer: false }, { text: "d) Mỹ biến miền Nam thành thuộc địa kiểu mới.", answer: true }]},
    { type: 'tf', text: "Về Nghị quyết 15 (1/1959):", options: [{ text: "a) Xác định cách mạng miền Nam sử dụng bạo lực.", answer: true }, { text: "b) Cấm đấu tranh vũ trang.", answer: false }, { text: "c) Kết hợp đấu tranh chính trị với vũ trang lật đổ Mỹ - Diệm.", answer: true }, { text: "d) Thắp sáng ngọn lửa cho phong trào Đồng khởi.", answer: true }]},
    { type: 'tf', text: "Về chiến lược 'Chiến tranh đặc biệt':", options: [{ text: "a) Kết hợp đấu tranh trên 3 vùng chiến lược.", answer: true }, { text: "b) Phong trào phá 'ấp chiến lược' làm phá sản xương sống của địch.", answer: true }, { text: "c) Mỹ dùng bom nguyên tử cứu vãn chiến lược.", answer: false }, { text: "d) Chiến thắng Ấp Bắc dấy lên thi đua giết giặc lập công.", answer: true }]},
    { type: 'tf', text: "Về Tổng tiến công Xuân Mậu Thân (1968):", options: [{ text: "a) Tấn công đồng loạt các đô thị, cơ quan đầu não địch.", answer: true }, { text: "b) Giải phóng hoàn toàn Sài Gòn trong đợt 1.", answer: false }, { text: "c) Làm lung lay ý chí xâm lược của Mỹ.", answer: true }, { text: "d) Buộc Mỹ phải đàm phán ở Pa-ri.", answer: true }]},
    { type: 'tf', text: "Về Trận 'Điện Biên Phủ trên không' (1972):", options: [{ text: "a) Mỹ ném bom rải thảm B-52 Hà Nội, Hải Phòng ép ta nhượng bộ.", answer: true }, { text: "b) Ta bắn rơi nhiều B-52, lập kì tích.", answer: true }, { text: "c) Thất bại này buộc Mỹ kí Hiệp định Giơ-ne-vơ.", answer: false }, { text: "d) Là đòn quyết định buộc Mỹ kí Hiệp định Pa-ri.", answer: true }]},
    { type: 'tf', text: "Về Hiệp định Pa-ri (1973):", options: [{ text: "a) Mỹ công nhận độc lập, chủ quyền, toàn vẹn lãnh thổ Việt Nam.", answer: true }, { text: "b) Mỹ rút hết quân đội Mỹ và đồng minh về nước.", answer: true }, { text: "c) Lực lượng cách mạng miền Nam phải giải giáp vũ khí.", answer: false }, { text: "d) Tạo bước ngoặt 'đánh cho Mỹ cút'.", answer: true }]},
    { type: 'tf', text: "Về vai trò miền Bắc trong chống Mỹ:", options: [{ text: "a) Vừa sản xuất, vừa chiến đấu chống chiến tranh phá hoại.", answer: true }, { text: "b) Là hậu phương lớn chi viện cho tiền tuyến.", answer: true }, { text: "c) Đường Trường Sơn là mạch máu nối Nam - Bắc.", answer: true }, { text: "d) Miền Bắc không bị Mỹ ném bom do luật quốc tế.", answer: false }]},
    { type: 'tf', text: "Về Tổng tiến công Xuân 1975:", options: [{ text: "a) Thực hiện qua 3 chiến dịch lớn.", answer: true }, { text: "b) Mở màn bằng trận Buôn Ma Thuột.", answer: true }, { text: "c) Mất 2 năm mới giải phóng Sài Gòn.", answer: false }, { text: "d) Chiến dịch Hồ Chí Minh kết thúc thắng lợi cuộc kháng chiến.", answer: true }]},
    { type: 'tf', text: "Về ý nghĩa cuộc kháng chiến chống Mỹ:", options: [{ text: "a) Kết thúc 21 năm chiến tranh chống Mỹ.", answer: true }, { text: "b) Bảo vệ thành quả Cách mạng tháng Tám.", answer: true }, { text: "c) Trở thành siêu cường châu Á.", answer: false }, { text: "d) Cổ vũ phong trào giải phóng dân tộc thế giới.", answer: true }]},
    { type: 'tf', text: "Về nguyên nhân thắng lợi của cuộc kháng chiến chống Pháp:", options: [{ text: "a) Sự lãnh đạo sáng suốt của Đảng và Hồ Chí Minh.", answer: true }, { text: "b) Sức mạnh khối đại đoàn kết toàn dân.", answer: true }, { text: "c) Sự suy yếu kinh tế của nước Mỹ.", answer: false }, { text: "d) Sự ủng hộ của nhân dân tiến bộ thế giới.", answer: true }]},
    { type: 'tf', text: "Về đường lối kháng chiến chống Pháp:", options: [{ text: "a) 'Toàn dân' là huy động sức mạnh mọi người dân.", answer: true }, { text: "b) 'Trường kì' là đánh nhanh thắng nhanh.", answer: false }, { text: "c) 'Toàn diện' là đánh trên mọi mặt trận.", answer: true }, { text: "d) 'Tự lực cánh sinh' là dựa vào sức mình là chính.", answer: true }]},
    { type: 'tf', text: "Về nguyên nhân thắng lợi của cuộc kháng chiến chống Mỹ:", options: [{ text: "a) Đường lối độc lập, tự chủ của Đảng.", answer: true }, { text: "b) Sức mạnh hậu phương miền Bắc, tiền tuyến miền Nam.", answer: true }, { text: "c) Liên Xô đem quân sang trực tiếp chiến đấu.", answer: false }, { text: "d) Đoàn kết chiến đấu của 3 nước Đông Dương.", answer: true }]}
];

// --- CHỦ ĐỀ 3: ĐỔI MỚI, ĐỐI NGOẠI & HỒ CHÍ MINH ---
const cd3_mcq = [
    { type: 'mcq', text: "Đại hội nào khởi xướng đường lối Đổi mới toàn diện đất nước?", options: ["Đại hội IV (1976).", "Đại hội V (1982).", "Đại hội VI (1986).", "Đại hội VII (1991)."], answer: 2 },
    { type: 'mcq', text: "Hoàn cảnh trong nước buộc Đảng ta tiến hành Đổi mới là gì?", options: ["Lạm phát phát triển nóng.", "Khủng hoảng kinh tế - xã hội trầm trọng do cơ chế bao cấp.", "Sức ép quân sự của Mỹ.", "Nông nghiệp cơ giới hóa hoàn toàn."], answer: 1 },
    { type: 'mcq', text: "Trọng tâm của đường lối Đổi mới (Đại hội VI) là gì?", options: ["Chính trị.", "Văn hóa.", "Kinh tế.", "Quốc phòng."], answer: 2 },
    { type: 'mcq', text: "Mô hình kinh tế tổng quát của Việt Nam thời kì Đổi mới là gì?", options: ["Tự cung tự cấp.", "Tư bản chủ nghĩa.", "Kinh tế thị trường định hướng XHCN.", "Kế hoạch hóa tập trung."], answer: 2 },
    { type: 'mcq', text: "Ngoại giao nhân dân ta cuối kỉ XIX - đầu kỉ XX chủ yếu nhằm?", options: ["Thiết lập thương mại châu Âu.", "Cầu viện quốc tế đánh đuổi Pháp.", "Phát triển giáo dục.", "Mở rộng lãnh thổ."], answer: 1 },
    { type: 'mcq', text: "Thành tựu ngoại giao đầu tiên của VNDCCH sau Cách mạng tháng Tám là?", options: ["Hiệp định Giơ-ne-vơ.", "Gia nhập LHQ.", "Hiệp định Sơ bộ và Tạm ước.", "Mỹ công nhận độc lập."], answer: 2 },
    { type: 'mcq', text: "Hiệp định Giơ-ne-vơ (1954) quan trọng vì:", options: ["các cường quốc công nhận các quyền dân tộc cơ bản.", "Mỹ bồi thường chiến tranh.", "Việt Nam gia nhập ASEAN.", "Việt Nam thống nhất hoàn toàn."], answer: 0 },
    { type: 'mcq', text: "Đàm phán Hiệp định Pa-ri (1973) kéo dài bao lâu?", options: ["1 năm.", "3 năm.", "Gần 5 năm.", "10 năm."], answer: 2 },
    { type: 'mcq', text: "Năm 1995 đánh dấu 3 sự kiện ngoại giao nào?", options: ["Gia nhập LHQ, bình thường hóa Trung Quốc, WTO.", "Gia nhập ASEAN, bình thường hóa Mỹ, kí Hiệp định khung với EU.", "Gia nhập APEC, ASEAN, bình thường hóa Nhật.", "Gia nhập WTO, bình thường hóa Mỹ, LHQ."], answer: 1 },
    { type: 'mcq', text: "Bản chất của Đổi mới ở Việt Nam là gì?", options: ["Từ bỏ chủ nghĩa xã hội.", "Đa nguyên đa đảng.", "Làm cho mục tiêu XHCN thực hiện hiệu quả bằng hình thức phù hợp.", "Quay lại phong kiến."], answer: 2 },
    { type: 'mcq', text: "Bước ngoặt trong hoạt động của Nguyễn Ái Quốc là sự kiện nào?", options: ["Gửi Bản yêu sách (1919).", "Đọc Sơ thảo Luận cương và tán thành gia nhập Quốc tế Cộng sản (1920).", "Thành lập Hội VN Cách mạng Thanh niên.", "Thành lập Đảng."], answer: 1 },
    { type: 'mcq', text: "Tác phẩm nào (1927) phác thảo đường lối cứu nước?", options: ["Bản án chế độ thực dân Pháp.", "Đường Kách mệnh.", "Con rồng tre.", "Nhật kí trong tù."], answer: 1 },
    { type: 'mcq', text: "Vai trò lớn nhất của Nguyễn Ái Quốc tại Hội nghị hợp nhất Đảng (1930) là?", options: ["Chỉ đạo khởi nghĩa.", "Thống nhất các tổ chức cộng sản, thông qua Cương lĩnh.", "Kêu gọi viện trợ Liên Xô.", "Soạn Luận cương chính trị."], answer: 1 },
    { type: 'mcq', text: "Năm 1941, Bác Hồ về nước làm việc tại đâu?", options: ["Pác Bó (Cao Bằng).", "Tân Trào.", "Bắc Sơn.", "Hà Nội."], answer: 0 },
    { type: 'mcq', text: "Tuyên ngôn Độc lập (2/9/1945) có ý nghĩa cốt lõi gì?", options: ["Kêu gọi Pháp rút.", "Khẳng định độc lập, khai sinh VNDCCH.", "Tuyên chiến với Nhật.", "Lập chế độ quân chủ."], answer: 1 },
    { type: 'mcq', text: "Tư tưởng cốt lõi của Hồ Chí Minh về con đường giải phóng dân tộc là gì?", options: ["Dựa vào phương Tây.", "Cách mạng tư sản.", "Giải phóng dân tộc gắn liền với con đường cách mạng vô sản.", "Cải lương."], answer: 2 },
    { type: 'mcq', text: "'Không có gì quý hơn độc lập, tự do' được nêu ra trong hoàn cảnh nào?", options: ["Tuyên ngôn Độc lập (1945).", "Toàn quốc kháng chiến (1946).", "Lời kêu gọi chống Mỹ (17/7/1966).", "Di chúc (1969)."], answer: 2 },
    { type: 'mcq', text: "Tư tưởng đại đoàn kết của Bác Hồ cô đúc trong câu nào?", options: ["'Đoàn kết, đoàn kết, đại đoàn kết. Thành công...'.", "'Không có gì quý hơn...'.", "'Dĩ bất biến, ứng vạn biến'.", "'Các Vua Hùng đã có công...'."], answer: 0 },
    { type: 'mcq', text: "Trong Di chúc, Bác dặn điều gì đầu tiên về Đảng?", options: ["Phát triển kinh tế.", "Xây dựng quân đội.", "Giữ gìn sự đoàn kết nhất trí của Đảng.", "Mở rộng ngoại giao."], answer: 2 },
    { type: 'mcq', text: "UNESCO tôn vinh Chủ tịch Hồ Chí Minh danh hiệu gì (1987)?", options: ["Nhà chính trị xuất sắc.", "Anh hùng giải phóng dân tộc và Nhà văn hóa kiệt xuất.", "Lãnh tụ công nhân.", "Nhà quân sự thiên tài."], answer: 1 },
    { type: 'mcq', text: "Ba chương trình kinh tế lớn (Đại hội VI, 1986) là gì?", options: ["Công nghiệp nặng, điện, khai khoáng.", "Lương thực - thực phẩm, hàng tiêu dùng, hàng xuất khẩu.", "Nông, công, dịch vụ.", "Giáo dục, y tế, văn hóa."], answer: 1 },
    { type: 'mcq', text: "Chính sách đối ngoại thời kì Đổi mới có phương châm gì?", options: ["Bế quan tỏa cảng.", "Muốn là bạn với tất cả các nước, vì hòa bình, độc lập.", "Chỉ quan hệ với nước XHCN.", "Liên minh quân sự lớn."], answer: 1 },
    { type: 'mcq', text: "Việt Nam chính thức gia nhập WTO vào năm nào?", options: ["1995.", "1997.", "2007.", "2015."], answer: 2 },
    { type: 'mcq', text: "Ai là người trực tiếp gửi Bản Yêu sách của nhân dân An Nam đến Hội nghị Véc-xai (1919)?", options: ["Phan Bội Châu.", "Phan Châu Trinh.", "Nguyễn Ái Quốc.", "Hồ Tùng Mậu."], answer: 2 },
    { type: 'mcq', text: "Nước đầu tiên công nhận và đặt quan hệ ngoại giao với VNDCCH (1/1950) là?", options: ["Liên Xô.", "Trung Quốc.", "Cuba.", "Pháp."], answer: 1 },
    { type: 'mcq', text: "Mặt trận ngoại giao trong chống Mỹ có vai trò gì?", options: ["Biểu tượng.", "Phối hợp với chính trị và quân sự, tạo sức mạnh tổng hợp.", "Quyết định duy nhất.", "Kêu gọi viện trợ kinh tế."], answer: 1 },
    { type: 'mcq', text: "Từ 1986 đến nay, nguyên tắc đối ngoại của Việt Nam là gì?", options: ["Độc lập, tự chủ, hòa bình, hợp tác và phát triển.", "Liên minh phòng thủ.", "Bế quan tỏa cảng.", "Sử dụng vũ lực."], answer: 0 },
    { type: 'mcq', text: "Nghệ thuật ngoại giao của Việt Nam hiện nay được ví với hình ảnh gì?", options: ["Cây tre.", "Cây tùng.", "Cây liễu.", "Hoa sen."], answer: 0 },
    { type: 'mcq', text: "Nguyễn Ái Quốc thành lập Hội Việt Nam Cách mạng Thanh niên tại đâu?", options: ["Hà Nội.", "Hồng Kông.", "Quảng Châu.", "Mạc Tư Khoa."], answer: 2 },
    { type: 'mcq', text: "Tờ báo nào là cơ quan ngôn luận của Hội Việt Nam Cách mạng Thanh niên?", options: ["Thanh niên.", "Người cùng khổ.", "Búa liềm.", "Đỏ."], answer: 0 },
    { type: 'mcq', text: "Hồ Chí Minh đọc Tuyên ngôn Độc lập tại đâu?", options: ["Nhà hát lớn Hà Nội.", "Quảng trường Ba Đình.", "Bến Nhà Rồng.", "Pác Bó."], answer: 1 },
    { type: 'mcq', text: "Cuộc Tổng tuyển cử đầu tiên bầu Quốc hội nước VNDCCH diễn ra vào ngày nào?", options: ["2/9/1945.", "6/1/1946.", "19/12/1946.", "20/11/1946."], answer: 1 },
    { type: 'mcq', text: "Việt Nam gia nhập APEC (Diễn đàn Hợp tác Kinh tế Châu Á - Thái Bình Dương) năm nào?", options: ["1995.", "1998.", "2007.", "2020."], answer: 1 },
    { type: 'mcq', text: "Cơ chế quản lý kinh tế nào bị xóa bỏ trong thời kì Đổi mới?", options: ["Thị trường.", "Tập trung, quan liêu, bao cấp.", "Khoán.", "Hạch toán."], answer: 1 },
    { type: 'mcq', text: "Một trong những bài học ngoại giao từ Hiệp định Pa-ri là gì?", options: ["Chỉ dựa vào quốc tế.", "Kết hợp sức mạnh thực lực và ngoại giao.", "Nhượng bộ lãnh thổ.", "Từ chối đàm phán đa phương."], answer: 1 },
    { type: 'mcq', text: "Đặc điểm của Đổi mới kinh tế Việt Nam là gắn liền với?", options: ["Bất ổn chính trị.", "Hội nhập kinh tế quốc tế.", "Chiến tranh.", "Xóa bỏ công nghiệp."], answer: 1 },
    { type: 'mcq', text: "Việt Nam giữ cương vị Ủy viên không thường trực HĐBA LHQ lần đầu tiên nhiệm kì nào?", options: ["2008-2009.", "2020-2021.", "1998-1999.", "2015-2016."], answer: 0 },
    { type: 'mcq', text: "Khẩu hiệu nào thể hiện tư tưởng chớp thời cơ của Bác Hồ trong tháng 8/1945?", options: ["Dĩ bất biến, ứng vạn biến.", "Dù phải đốt cháy cả dãy Trường Sơn cũng phải giành cho được tự do độc lập.", "Không có gì quý hơn độc lập tự do.", "Sát Thát."], answer: 1 },
    { type: 'mcq', text: "Hình thức đổi mới chính trị ở Việt Nam là gì?", options: ["Đổi mới tổ chức và phương thức hoạt động của hệ thống chính trị.", "Đa nguyên đa đảng.", "Giải tán Quốc hội.", "Thay đổi hiến pháp tư bản."], answer: 0 },
    { type: 'mcq', text: "Việt Nam ký kết Hiệp định Thương mại tự do Việt Nam - EU (EVFTA) vào năm nào?", options: ["2007.", "2015.", "2019.", "2022."], answer: 2 }
];

const cd3_tf = [
    { type: 'tf', text: "Về sự cần thiết phải Đổi mới (1986):", options: [{ text: "a) Kinh tế khủng hoảng, lạm phát gần 800%.", answer: true }, { text: "b) Đời sống nhân dân gặp vô vàn khó khăn.", answer: true }, { text: "c) Mô hình kinh tế kế hoạch hóa đã bộc lộ nhược điểm.", answer: true }, { text: "d) Sức ép bị Mỹ xâm lược quân sự.", answer: false }]},
    { type: 'tf', text: "Về quan điểm Đổi mới:", options: [{ text: "a) Đổi mới toàn diện, đồng bộ.", answer: true }, { text: "b) Đổi mới chính trị là thực hiện đa nguyên đa đảng.", answer: false }, { text: "c) Trọng tâm là đổi mới kinh tế.", answer: true }, { text: "d) Nhằm xây dựng CNXH hiệu quả hơn.", answer: true }]},
    { type: 'tf', text: "Về thành tựu Đổi mới:", options: [{ text: "a) Việt Nam trở thành nước có thu nhập trung bình.", answer: true }, { text: "b) Tốc độ tăng trưởng luôn ở mức âm.", answer: false }, { text: "c) Đời sống nhân dân cải thiện rõ rệt.", answer: true }, { text: "d) Quốc phòng, an ninh được tăng cường.", answer: true }]},
    { type: 'tf', text: "Về hạn chế, thách thức của Đổi mới:", options: [{ text: "a) Nền kinh tế đã hoàn hảo.", answer: false }, { text: "b) Nguy cơ tụt hậu về kinh tế.", answer: true }, { text: "c) Tham nhũng, suy thoái tư tưởng ở một bộ phận cán bộ.", answer: true }, { text: "d) Khoảng cách phân hóa giàu nghèo gia tăng.", answer: true }]},
    { type: 'tf', text: "Về ngoại giao đầu thế kỉ XX:", options: [{ text: "a) Thực hiện phong trào Đông Du cầu viện Nhật.", answer: true }, { text: "b) Tranh thủ được viện trợ quân sự phương Tây.", answer: false }, { text: "c) Nguyễn Ái Quốc thiết lập mối liên hệ quốc tế.", answer: true }, { text: "d) Mở rộng tầm nhìn người Việt ra thế giới.", answer: true }]},
    { type: 'tf', text: "Về ngoại giao 1945-1946:", options: [{ text: "a) Vận dụng sách lược 'Hòa để tiến'.", answer: true }, { text: "b) Lợi dụng mâu thuẫn Tưởng - Pháp.", answer: true }, { text: "c) Nhượng bộ nguyên tắc độc lập.", answer: false }, { text: "d) Giúp bảo toàn lực lượng, chuẩn bị kháng chiến.", answer: true }]},
    { type: 'tf', text: "Về đàm phán Giơ-ne-vơ (1954):", options: [{ text: "a) Đoàn đại biểu do Phạm Văn Đồng dẫn đầu.", answer: true }, { text: "b) Tạo đà từ chiến thắng Điện Biên Phủ.", answer: true }, { text: "c) Quy định nước ta bị chia cắt vĩnh viễn.", answer: false }, { text: "d) Biết lợi dụng mâu thuẫn nước lớn.", answer: true }]},
    { type: 'tf', text: "Về ngoại giao thời chống Mỹ:", options: [{ text: "a) Là mặt trận chiến lược.", answer: true }, { text: "b) Hiệp định Pa-ri không yêu cầu miền Bắc rút quân.", answer: true }, { text: "c) Từ chối đàm phán cho đến khi giải phóng.", answer: false }, { text: "d) Mở ra cơ hội chiến lược giải phóng miền Nam.", answer: true }]},
    { type: 'tf', text: "Về ngoại giao Đổi mới:", options: [{ text: "a) Chuyển sang đa phương hóa, đa dạng hóa.", answer: true }, { text: "b) Bình thường hóa với Mỹ, Trung Quốc.", answer: true }, { text: "c) Kinh tế ngoại giao bị xem nhẹ.", answer: false }, { text: "d) Phá vỡ thế bị bao vây, cô lập.", answer: true }]},
    { type: 'tf', text: "Về 'Ngoại giao cây tre':", options: [{ text: "a) Kiên định nguyên tắc, linh hoạt sách lược.", answer: true }, { text: "b) Gió chiều nào che chiều ấy.", answer: false }, { text: "c) Dựa trên sức mạnh đại đoàn kết.", answer: true }, { text: "d) Nâng cao vị thế quốc tế.", answer: true }]},
    { type: 'tf', text: "Về tìm đường cứu nước (1911-1920):", options: [{ text: "a) Ra đi với khát vọng tự do.", answer: true }, { text: "b) Khảo sát thực tiễn nhiều nước.", answer: true }, { text: "c) Đi theo con đường tư sản.", answer: false }, { text: "d) Đọc Luận cương của Lê-nin giúp tìm đường đúng.", answer: true }]},
    { type: 'tf', text: "Về chuẩn bị lập Đảng:", options: [{ text: "a) Truyền bá chủ nghĩa Mác - Lênin.", answer: true }, { text: "b) Chuẩn bị tư tưởng, chính trị, tổ chức.", answer: true }, { text: "c) Trực tiếp lãnh đạo khởi nghĩa Yên Bái.", answer: false }, { text: "d) Sáng lập Cương lĩnh đầu tiên.", answer: true }]},
    { type: 'tf', text: "Về lãnh đạo Cách mạng tháng Tám:", options: [{ text: "a) Chủ trì Trung ương 8, chuyển hướng chiến lược.", answer: true }, { text: "b) Sáng lập Mặt trận Việt Minh.", answer: true }, { text: "c) Cầm quân đánh Phủ Khâm sai.", answer: false }, { text: "d) Ra Lời kêu gọi Tổng khởi nghĩa.", answer: true }]},
    { type: 'tf', text: "Về tư tưởng độc lập dân tộc gắn với CNXH:", options: [{ text: "a) Là sợi chỉ đỏ xuyên suốt.", answer: true }, { text: "b) Độc lập dân tộc là tiền đề cho CNXH.", answer: true }, { text: "c) CNXH bảo đảm vững chắc độc lập.", answer: true }, { text: "d) Việt Nam không cần dân chủ mà tiến thẳng CNXH.", answer: false }]},
    { type: 'tf', text: "Về vai trò trong hai kháng chiến:", options: [{ text: "a) Là Tổng Tư lệnh tối cao dẫn dắt dân tộc.", answer: true }, { text: "b) Vạch đường lối kháng chiến toàn dân, toàn diện.", answer: true }, { text: "c) Nhìn thấy miền Nam giải phóng trước khi mất.", answer: false }, { text: "d) Lời kêu gọi cổ vũ tinh thần chiến đấu.", answer: true }]},
    { type: 'tf', text: "Về nghệ thuật ngoại giao Hồ Chí Minh:", options: [{ text: "a) 'Dĩ bất biến, ứng vạn biến'.", answer: true }, { text: "b) Kiên định chủ quyền, linh hoạt sách lược.", answer: true }, { text: "c) Luôn dùng vũ lực đe dọa.", answer: false }, { text: "d) Tranh thủ sự ủng hộ quốc tế.", answer: true }]},
    { type: 'tf', text: "Về đạo đức, phong cách:", options: [{ text: "a) Tấm gương Cần, Kiệm, Liêm, Chính.", answer: true }, { text: "b) Giản dị, gần gũi.", answer: true }, { text: "c) Quan liêu, xa rời thực tế.", answer: false }, { text: "d) Thống nhất giữa lời nói và việc làm.", answer: true }]},
    { type: 'tf', text: "Về sự tôn vinh quốc tế:", options: [{ text: "a) Được bạn bè quốc tế kính trọng.", answer: true }, { text: "b) UNESCO vinh danh Anh hùng giải phóng dân tộc, Nhà văn hóa.", answer: true }, { text: "c) Nhận giải Nobel Hòa bình 1973.", answer: false }, { text: "d) Nhiều nước dựng tượng, đặt tên đường.", answer: true }]},
    { type: 'tf', text: "Về tư tưởng Hồ Chí Minh hiện nay:", options: [{ text: "a) Là kim chỉ nam của Đảng.", answer: true }, { text: "b) Là tài sản tinh thần vô giá.", answer: true }, { text: "c) Không còn phù hợp.", answer: false }, { text: "d) Soi đường cho xây dựng và hội nhập.", answer: true }]},
    { type: 'tf', text: "Về Di chúc:", options: [{ text: "a) Là tâm huyết cuối cùng.", answer: true }, { text: "b) Khẳng định niềm tin chống Mỹ thắng lợi.", answer: true }, { text: "c) Yêu cầu từ bỏ quyền lãnh đạo của Đảng.", answer: false }, { text: "d) Dặn giữ gìn sự đoàn kết của Đảng.", answer: true }]}
];


// =========================================================================
// XÂY DỰNG DATA CHÍNH (RÁP NỐI 10 TEST/CHỦ ĐỀ)
// =========================================================================

// Hàm hỗ trợ xáo trộn tĩnh để tạo ra 10 mảng test khác nhau từ 40 MCQ / 20 TF
function getTests(pool, count) {
    let res = {};
    let isTF = pool.length < 30; // TF có 20 câu, MCQ có 40 câu
    for (let i = 1; i <= 10; i++) {
        let test = [];
        for (let j = 0; j < 10; j++) {
            // Công thức trộn chỉ số tĩnh đảm bảo không trùng lặp toàn bộ
            let index = (i * 3 + j * (isTF ? 1 : 2) + j) % pool.length;
            test.push(pool[index]);
        }
        res['test' + i] = test;
    }
    return res;
}

const dataKhoi12 = {
    1: {
        title: "Chủ đề 1 & 2: Thế giới sau Chiến tranh lạnh & ASEAN",
        exercises: {
            mcq: getTests(cd1_mcq, 10),
            tf: getTests(cd1_tf, 10)
        }
    },
    2: {
        title: "Chủ đề 3: Cuộc chiến tranh GPDT và BV Tổ quốc ở VN (1945-1975)",
        exercises: {
            mcq: getTests(cd2_mcq, 10),
            tf: getTests(cd2_tf, 10)
        }
    },
    3: {
        title: "Chủ đề 4, 5, 6: Đổi mới, Đối ngoại & Hồ Chí Minh",
        exercises: {
            mcq: getTests(cd3_mcq, 10),
            tf: getTests(cd3_tf, 10)
        }
    }
};
